### ISSUE TITLE
Does sim3C accept self-prepared community abundance profile in Hi-C mode?

### ISSUE THREAD

**Issue by zengxiaofei** [cerebis/sim3C#21]
Hi Matthew,

I gave sim3C a self-prepared community abundance profile in Hi-C mode like this:

```Bash
$ sim3C rice_genome_chr0102.fa sim.fastq --profile mycom.txt --dist uniform -n 25000000 -l 150 -e MboI -m hic --seed 12345
```

mycom.txt:

```
#chrom	cell	abundance	copy_number
9311_Chr01	cell1	0.25	1
9311_Chr02	cell1	0.25	1
Nipponbare_Chr01	cell1	0.25	1
Nipponbare_Chr02	cell1	0.25	1
```

But sim3C generated a new `profile.tsv` in which cell & abundance are different from `mycom.txt`:

```
#chrom	cell	abundance	copy_number
9311_Chr01	9311_Chr01	0.568757	1
9311_Chr02	9311_Chr02	0.193565	1
Nipponbare_Chr01	Nipponbare_Chr01	0.112525	1
Nipponbare_Chr02	Nipponbare_Chr02	0.125154	1
```

So I have no idea whether my profile has been adopted. 

Another question is will sim3C simulate inter-chromosome contacts in Hi-C mode?

Thanks! :smile:
Xiaofei

**Comment by cerebis** [comment]
Sorry Xiaofei, you've found a bit of a usability bug.

If you provide a user-based profile, don't use the `--dist uniform` option.
In doing so, you're asking sim3C to create a profile and use the file-name
you provided.

So, for your case, just provide the profile file-name.

Regards,
Matt DeMaere

**Comment by zengxiaofei** [comment]
I got it! Thank you!
