### ISSUE TITLE
Simulation without restriction enzymes

### ISSUE THREAD

**Issue by ValentinaBoP** [cerebis/sim3C#22]
Hi!

I would need to simulate Omni-C libraries for which a DNAase is used instead of restriction enzymes. I was wondering: is it possible to easily tweak the code of sim3C to avoid the digestion step? Is it something you could add as feature of the tool?

Thanks for your help!
Valentina

**Comment by cerebis** [comment]
Sorry for the very slow reply, but there is a "dnase" mode.
